//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SolicitudTarjeta
    {
        public int Codigo { get; set; }
        public int CodigoCuenta { get; set; }
        public string EstadoCivil { get; set; }
        public string CondicionLaboral { get; set; }
        public decimal IngresoMensual { get; set; }
        public string ProductoDeseado { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
    }
}
