//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarjetaDeCredito
    {
        public int Codigo { get; set; }
        public int CodigoCuenta { get; set; }
        public string NumeroDeTarjeta { get; set; }
        public string Tipo { get; set; }
        public int AnoExpiracion { get; set; }
        public int MesExpiracion { get; set; }
        public int CV2 { get; set; }
    
        public virtual Cuenta Cuenta { get; set; }
    }
}
